version: '3.8'

services: 
  database:
    container_name: project-database
    build: 
      context: .
      target: postgres
    environment:
      - POSTGRES_PASSWORD=mrc201
  backend:
    container_name: project-backend
    build:
      context: .
      target: fastify
    ports:
      - 3000:3000
    command: bash -c "npx prisma migrate deploy && npm start"