version: '3.8'

services: 
  database:
    image: postgres:alpine
    working_dir: /usr/db
    container_name: project-database
    networks:
      - project
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mrc201
  backend:
    container_name: project-backend
    depends_on:
      - database
    networks:
      - project
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: .
      target: fastify
    ports:
      - 3000:3000
    command: bash -c "npx prisma migrate deploy && npm run dev"

networks:
  project:

volumes:
  db-storage: