version: '3.8'

services: 
  database:
    build:
      context: .
      target: postgres
    container_name: project-database
    networks:
      - project
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mrc201
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 25s
      retries: 5
    
  backend:
    container_name: project-backend
    depends_on:
      - database
    networks:
      - project
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - public-img:/usr/src/app/public
    build:
      context: .
      target: fastify
    ports:
      - 3000:3000
    command: bash -c "npx prisma db push && npm run dev"

networks:
  project:

volumes:
  db-storage:
  public-img: