version: '3.8'

services: 
  database:
    image: postgres:15.2-alpine
    working_dir: /db
    container_name: project-database
    networks:
      - project
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mrc201
  backend:
    container_name: project-backend
    networks:
      - project
    build:
      context: .
      target: fastify
    ports:
      - 3000:3000
    command: bash -c "npx prisma migrate deploy && npm start"

networks:
  project:

volumes:
  db-storage: